import Header from "@/Components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Providers>
          <div className="limiter">
            <div className="container-login100">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
